// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFx_ibbCtidtPn71Wa6KChKN-e_dYLH-4',
    appId: '1:629942897511:web:3f950232eede0912f3fdc2',
    messagingSenderId: '629942897511',
    projectId: 'fultterauth-1aecc',
    authDomain: 'fultterauth-1aecc.firebaseapp.com',
    storageBucket: 'fultterauth-1aecc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNVenvbwXyh8EsUyoEYfUJZ4i_mpsm_o',
    appId: '1:629942897511:android:33740ea579531942f3fdc2',
    messagingSenderId: '629942897511',
    projectId: 'fultterauth-1aecc',
    storageBucket: 'fultterauth-1aecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFCnYJJmNu69Db7O5pir0biYxiW8S-QCE',
    appId: '1:629942897511:ios:ab77739c0771f545f3fdc2',
    messagingSenderId: '629942897511',
    projectId: 'fultterauth-1aecc',
    storageBucket: 'fultterauth-1aecc.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFCnYJJmNu69Db7O5pir0biYxiW8S-QCE',
    appId: '1:629942897511:ios:ab77739c0771f545f3fdc2',
    messagingSenderId: '629942897511',
    projectId: 'fultterauth-1aecc',
    storageBucket: 'fultterauth-1aecc.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFx_ibbCtidtPn71Wa6KChKN-e_dYLH-4',
    appId: '1:629942897511:web:44fd3b248a80e683f3fdc2',
    messagingSenderId: '629942897511',
    projectId: 'fultterauth-1aecc',
    authDomain: 'fultterauth-1aecc.firebaseapp.com',
    storageBucket: 'fultterauth-1aecc.firebasestorage.app',
  );
}
